### PR TITLE
Make package available with a composer

### PR DESCRIPTION
**Pull request by alekseykuleshov**
Hello!

I liked your library very much. Although I want to add it to my project via composer. 
This pull request provides this (even no need to submit it to https://packagist.org/).

The following should be added to project `composer.json`:
```
    "require": {
        "Fab1en/rocket-chat-rest-client": "dev-master"
    },
    "repositories": [
        {
            "type": "git",
            "url":  "git@github.com:Fab1en/rocket-chat-rest-client.git"
        }
    ],
```
Or, `repositories` can be removed after adding to https://packagist.org/

And, as a good feature, composer autoloading is in place. No need to `require` files. 

Could you please let me know your thoughts?

Thank you,
Alex

### CODE REVIEW

**Comment by Fab1en** [comment]
That's amazing, thanks a lot @alekseykuleshov !
But I don't understand how I can setup autoloading with composer. Do I have to include a composer php file somewhere ? Could you update the README to reflect this and remove the `require_once` directives ?

Thanks

**Comment by alekseykuleshov** [comment]
@Fab1en Here is the description how composer autoloading works: https://getcomposer.org/doc/01-basic-usage.md#autoloading

I would be happy to update README, but to make it in a proper way, the package has to be registered there: https://packagist.org/ Thus it will available in composer repo (so nobody has to specify it explicitly). But it requires composer.json in your `master` branch. So, I can propose the following:

1) You merge this pull request;
2) You register it at packagist;
3) Once available there, I'll do an upcoming pull request with README update.

Does this sounds like a plan?

And I think I'll do small pull request to send user roles too, it seems I would need them too.

Thank you,
Alex

**Comment by alekseykuleshov** [comment]
PS. Once done, you would be able to drop Httpful phar from your repo, but just add to dependencies of your package. And it will be there easily after composer install. No need in extra requires in code.

**Comment by alekseykuleshov** [comment]
@Fab1en Hello, sorry for being annoying. I already have some more additions to the functionality, based on this one. I need this one to be merged to make a pull request for them. Could you please update me?

**Comment by Fab1en** [comment]
Sorry for the delay @alekseykuleshov . The pull request is now merged. 
I tried to submit the package on packagist.org, but the name is invalid : 
> The package name Fab1en/rocket-chat-rest-client is invalid, it should not contain uppercase characters. We suggest using fab1en/rocket-chat-rest-client instead.
Do I have to change my github username and thus modify all my repositories to comply to this recommendation ? In that case, would could we use your fork instead to register the package ?

**Comment by alekseykuleshov** [comment]
@Fab1en I don't think you have to change your username. I think 

1) changing the package name here: https://github.com/Fab1en/rocket-chat-rest-client/blob/master/composer.json#L2 to meet the requirements
2) specify it in as it's in composer.json while submitting to packagist 
3) and leave repo url as it is 

would be enough. 

Could you please thy this?

**Comment by Fab1en** [comment]
Yes, I just changed the package name, and now it is registered on packagist : https://packagist.org/packages/fab1en/rocket-chat-rest-client

**Comment by alekseykuleshov** [comment]
@Fab1en Ok, that' perfect! I'll do a pull request for readme changes and some functionality extension soon!

**Comment by Fab1en** [comment]
Great ! Thanks a lot for your help and your patient explanations.

**Pull request merged**
