### PR TITLE
Update README, move httpful into dependencies, add "invite" for groups and channels

### PR DESCRIPTION
**Pull request by alekseykuleshov**
@Fab1en Here it's. The changes are described in pull request name.

### CODE REVIEW

**Comment by alekseykuleshov** [comment]
@Fab1en Sorry for disturbing you again, have you have a chance to review this?

**Comment by Fab1en** [comment]
Thanks for your work @alekseykuleshov . I installed composer and tested the class autoloading on my side and that is working well.

**Comment by alekseykuleshov** [comment]
@Fab1en Just for usability, you can do a release of the package, so someone can stuck to current version instead of having it updated with every commit. So, the can do:

```
{
    "require": {
        "fab1en/rocket-chat-rest-client": "0.0.1"
    }
}
```

and always be on a version they know it works for them. Kind of a stable release.
It's not required, but can be handy in some cases.

It can be done here: https://github.com/Fab1en/rocket-chat-rest-client/releases

Thank you for your help! The library fits my need as per now, but I expect more requirements coming, so I think it will be extended again.

**Comment by Fab1en** [comment]
Done !

**Pull request merged**
